### PR TITLE
Make syntax highlighting optional.

### LINKED ISSUE #4: Slow browsing
Loading this trace (vscode 1.72) takes forever. In particular a few seconds before the UI shows the card, then a few second before each card shows up its goal text. The third card text is "Cut", and it still takes time for it to appear.

If I had to point the finger, it would be syntax highlighting code. Is there an easy way to disable it, so that I can validate or refuse this thesis?

[trace-qui-rame.js.gz](https://github.com/LPCIC/elpi-lang/files/9851403/trace-qui-rame.js.gz)

CC @jwintz

### PR DESCRIPTION
**Pull request by jwintz**
`0.2.1` - Make highlighting optional:

- [x] Adds a boolean option for syntax highlighting in settings
- [x] Respect this option for each tracing context (open, watch, trace)
- [x] Improve the rendering of rules should highlighting be deactivated
- [x] Effectively increases performance on large traces

`0.2.2` - On the packaging stack:

- [x] Fallback to `npm` for all dependencies
- [x] Use minified assets exclusively
- [x] Introspect presence of required binaries in `PATH`

`0.2.3` - Ergonomy:

- [x] Better notifications: link the settings, implement callbacks on buttons
- [x] Pixel perfect scrolling when jumping from cards to cards
- [x] Understand how to handle node version for marketplace

### CODE REVIEW

**Comment by gares** [comment]
thanks for the quick fix, I'll try it out on Monday and release

**Comment by gares** [comment]
I did push here a CI file so that one can test the new extension more easily.

**Comment by gares** [comment]
Ci seems to build a usable extension, but the icons are not there, so I guess a package is missing (or my build commands are incomplete).

I've also discovered a little inconvenience: if `elpi-trace-browser` is not present in the path the extension hangs while loading the trace, but does not show an error message (you can see it in the JS console).

Said that, with syntax highlight off, the trace is quite speedy now.

**Comment by jwintz** [comment]
Well I’ve checked the recipe and it looks fine to me. I suggest I take this opportunity to fully rely on npm as we mentioned earlier. This will also allow to check requirements correctly without hanging.

**Comment by jwintz** [comment]
I’ll keep pushing fixes to this very branch to have CI produce packages we can easily test.

**Comment by gares** [comment]
> I suggest I take this opportunity to fully rely on npm as we mentioned earlier.

OK!

> This will also allow to check requirements correctly without hanging.

OK, but w.r.t. the elpi-trace-browser, it is a runtime dependency not part of npm, so I think it is the extension which should just complain loudly if it is not found. (assuming this is the requirement you talk about).

**Comment by jwintz** [comment]
Don't you mean `elpi-trace-elaborator` ?

**Comment by gares** [comment]
> Don't you mean `elpi-trace-elaborator` ?

Yes

Btw, it seems we can also upload to the market via CI, I'd be all for that:
https://code.visualstudio.com/api/working-with-extensions/continuous-integration

**Comment by jwintz** [comment]
Agreed ! On the master branch though I would say ...

PS: I'm almost done, so we'll soon be able to test the generated packages for the feature branch.

**Comment by jwintz** [comment]
Oh my, those jobs are quick and clean ... I'll leave it to you to check the candidate packages.

**Comment by gares** [comment]
So it installs
```
$ code --install-extension ./elpi-lang-0.2.2.vsix
(node:555359) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
Extension 'elpi-lang-0.2.2.vsix' was successfully installed.
```
but I don't see the icons unless I reload the window (maybe it is inevitable, not a big deal but some extensions tell you to reload the window, maybe it is as simple as setting a boolean):
Screenshot from 2022-11-21 14-28-50
If the `elpi-trace-elaborator` in not there, then I get a nice message!

So IMO this is OK

**Comment by gares** [comment]
If we set up automatic deployment, we can do it for tags only as the doc I linked above does.
GH lets you create a release (and a corresponding tag very easily) on master. That is the trigger I guess.

I've no clue which node job (which node version) should be used to prepare the artifact which is uploaded in the end.
I added two jobs just because this is what the examples were doing.

**Comment by jwintz** [comment]
> but I don't see the icons unless I reload the window (maybe it is inevitable, not a big deal but some extensions tell you to reload the window, maybe it is as simple as setting a boolean)

Hummm, can't reproduce ... Maybe that is for a previous version was installed. I'll check if we have callbacks on extension install or load.

**Comment by jwintz** [comment]
> I've no clue which node job (which node version) should be used to prepare the artifact which is uploaded in the end.

Screenshot from 2022-11-21 15-28-32

I'm desperately looking for the history of node versions used by visual studio over time to answer this one ...

**Comment by jwintz** [comment]
```
VSCode	Node	Electron	Chrome
1.71.x	16.14.2	19.0.12	102.0.5005.167
1.70.x	16.13.2	18.3.5	100.0.4896.160
1.69.x	16.13.2	18.3.5	100.0.4896.160
1.68.x	16.13.0	17.4.7	98.0.4758.141
1.67.x	16.13.0	17.4.1	98.0.4758.141
1.66.x	16.13.0	17.2.0	98.0.4758.109
1.65.x	14.16.0	13.5.2	91.0.4472.164
1.64.x	14.16.0	13.5.2	91.0.4472.164
1.63.x	14.16.0	13.5.2	91.0.4472.164
1.62.x	14.16.0	13.5.2	91.0.4472.164
1.61.x	14.16.0	13.5.1	91.0.4472.164
1.60.x	14.16.0	13.1.8	91.0.4472.164
1.59.x	14.16.0	13.1.7	91.0.4472.124
1.58.x	14.16.0	12.0.13	89.0.4389.128
1.57.x	14.16.0	12.0.7	89.0.4389.128
1.56.x	14.16.0	12.0.4	89.0.4389.114
1.55.x	12.18.3	11.3.0	87.0.4280.141
1.54.x	12.18.3	11.3.0	87.0.4280.141
1.53.x	12.18.3	11.2.1	87.0.4280.141
1.52.x	12.14.1	9.3.5	83.0.4103.122
1.51.x	12.14.1	9.3.3	83.0.4103.122
1.50.x	12.14.1	9.2.1	83.0.4103.122
1.49.x	12.14.1	9.2.1	83.0.4103.122
1.48.x	12.8.1	7.3.2	78.0.3904.130
1.47.x	12.8.1	7.3.2	78.0.3904.130
1.46.x	12.8.1	7.3.1	78.0.3904.130
1.45.x	12.8.1	7.2.4	78.0.3904.130
1.44.x	12.8.1	7.1.11	78.0.3904.130
1.43.x	12.8.1	7.1.11	78.0.3904.130
1.42.x	12.4.0	6.1.6	76.0.3809.146
1.41.x	12.4.0	6.1.6	76.0.3809.146
1.40.x	12.4.0	6.1.6	76.0.3809.146
1.39.x	10.11.0	4.2.10	69.0.3497.128
1.38.x	10.11.0	4.2.10	69.0.3497.128
1.37.x	10.11.0	4.2.10	69.0.3497.128
1.36.x	10.11.0	4.2.10	69.0.3497.128
1.35.x	10.2.0	3.1.8	66.0.3359.181
1.34.x	10.2.0	3.1.8	66.0.3359.181
1.33.x	10.2.0	3.1.6	66.0.3359.181
1.32.x	10.2.0	3.1.6	66.0.3359.181
1.31.x	10.2.0	3.1.2	66.0.3359.181
1.30.x	8.9.3	2.0.12	61.0.3163.100
1.29.x	8.9.3	2.0.12	61.0.3163.100
1.28.x	8.9.3	2.0.9	61.0.3163.100
1.27.x	8.9.3	2.0.7	61.0.3163.100
1.26.x	8.9.3	2.0.5	61.0.3163.100
1.25.x	7.9.0	1.7.12	58.0.3029.110
```

- VSCode 1.65 has been released in 02/2022
- VSCode 1.55 has been released in 03/2021

- The oldest Node LTS version still having support (5 months to go at the time of writing this message) is 14

**Comment by jwintz** [comment]
Will add some callbacks on various messages as in the following screenshot. Hold the merge for now.

Screenshot from 2022-11-22 10-04-26

**Comment by jwintz** [comment]
On the node version for packaging: since vscode automatically updates itself, I would go for the current node version only, being 16 right now. Note that I used to build packages using node 18 that are backwards compatible with the version 16 being run by vscode.

Jumping from card to card is now fixed as scrolling goes (my bad), it is also possible to jump to the relevant subset of settings for this extension, e.g. when a binary has not been found. Changelog and versions updated to 0.2.3.

Should you try installing the corresponding artifact, could you please close any elpi trace view beforehand and uninstall the extension as well before installing the new extension and opening the trace view once more, so that I can have more clues on the initial icon display ?

**Comment by gares** [comment]
I cannot reproduce the icons problem, so nevermind.

**Comment by gares** [comment]
Sorry, I did not forget about this one, but I'm super busy this week and the next one.
I wanted to add the code to publish the extension via CI and them merge, but I won't have the time before Dec 12 :-/

**Comment by gares** [comment]
Here the link to the doc, there is an event which can trigger a CI run when a new release is published: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

**Comment by gares** [comment]
@jwintz the PR is merged and CI is set to publish the extension (to both the MS market and the open vsx one) whenever:
- a tag is created
- one runs the workflow by hand

Of course the access tokens will eventually expire, but at least for some months the whole thing should work.

I've only one question. It seems we still purge some files:

https://github.com/LPCIC/elpi-lang/blob/0f6b207c382981d72dacd687fc38c011a8bd2438/package.json#L179

Is this OK? The extension works, and I get colors, so it seems OK, but looks odd no?

**Comment by jwintz** [comment]
> I've only one question. It seems we still purge some files. Is this OK?

It is. We only use `shiki` since, at the time of writing, `vscode` highlighting engine was **not** exposed via an API to be used by extensions. It believe it is still not.

So `shiki`, as a general purpose highlighting package comes with as many languages as it can, through `npm`, but we use none of them. Instead, we instantiate the highlighting engine on `elpi`'s grammar that is otherwise available and used in the extension.

https://github.com/LPCIC/elpi-lang/blob/0f6b207c382981d72dacd687fc38c011a8bd2438/src/provider.ts#L72-L75

In the end, we strip any language grammar to keep the bundle as light as possible.

**Pull request merged**
